export const trips = [
  {
    id: 1,
    img: "/spiti.jpg",
    name: "Spiti Winter Wonderland - Snow Trek Adventure",
    slug: "spiti-winter-wonderland",
    partner: "WanderOn",
    location: "Spiti Valley",
    duration: "7 Days",
    groupSize: "15-20",
    rating: "4.8",
    difficulty: "Moderate",
    startCity: "Manali, HP",
    price: "24999",
    description:
      "Experience the magic of Spiti Valley in winter with snow-covered landscapes and pristine monasteries.",
    itinerary: [
      {
        id: 1,
        heading: "Arrive in Manali",
        description: "Meet the group and briefing session",
      },
      {
        id: 2,
        heading: "Manali to Kaza",
        description: "Drive through stunning landscapes",
      },
      {
        id: 3,
        heading: "Explore Kaza",
        description: "Visit local monasteries and villages",
      },
    ],
    inclusions: ["Accomodation", "Meals", "Transportation", "Guide"],
    exclusions: ["Personal expenses", "Travel insurance", "Tips"],
    highlights: [
      "ChandraTal Lake",
      "Key Monastery",
      "Kibber Village",
      "Pin Valley",
    ],
  },
  {
    id: 2,
    img: "/meghalaya.jpg",
    name: "Meghalaya Living Root Bridges & Waterfalls",
    slug: "meghalaya-living-root-bridges",
    partner: "Safarnama",
    location: "Meghalaya",
    duration: "5 Days",
    groupSize: "12-18",
    rating: "4.9",
    difficulty: "Easy",
    startCity: "Shillong, Meghalaya",
    price: "18999",
    description:
      "Discover the wettest place on Earth with iconic living root bridges and cascading waterfalls.",
    itinerary: [
      {
        id: 1,
        heading: "Arrive in Shillong",
        description: "Orientation and city tour",
      },
      {
        id: 2,
        heading: "Cherrapunji",
        description: "Visit waterfalls and caves",
      },
    ],
    inclusions: [
      "Double Decker Root Bridge",
      "Meals",
      "Transportation",
      "Guide",
    ],
    exclusions: ["Personal expenses", "Travel insurance"],
    highlights: [
      "Double Decker Root Bridge",
      "Nohkalikai Falls",
      "Dawki River",
      "Mawlynnong",
    ],
  },
  {
    id: 3,
    img: "/ladakh.jpg",
    name: "Ladakh Complete Adventure - Lakes & Passes",
    slug: "ladakh-heaven-on-earth",
    partner: "Go4Explore",
    location: "Ladakh",
    duration: "9 Days",
    groupSize: "10-15",
    rating: "4.7",
    difficulty: "Challenging",
    startCity: "Leh",
    price: "32999",
    description:
      "Ultimate Ladakh adventure covering high-altitude passes, pristine lakes, and ancient monasteries.",
    itinerary: [
      {
        id: 1,
        heading: "Arrival in Leh",
        description: "Acclimatization day",
      },
      {
        id: 2,
        heading: "Leh Local",
        description: "Monastery circuit",
      },
    ],
    inclusions: ["Accomodation", "Meals", "Transportation", "Permits", "Guide"],
    exclusions: ["Airfare", "Personal expenses", "Travel insurance"],
    highlights: [
      "Pangong Tso",
      "Nubra Valley",
      "Khardung La",
      "Thiksey Monastery",
    ],
  },
  {
    id: 4,
    img: "/goa.jpg",
    name: "Goa Beach Retreat - Sun, Sand & Adventure",
    slug: "goa-sea-and-fishes",
    partner: "Wander Saga",
    location: "Goa",
    duration: "4 Days",
    groupSize: "20-25",
    rating: "4.6",
    difficulty: "Easy",
    startCity: "Goa",
    price: "12999",
    description:
      "Perfect beach getaway with water sports, beach parties, and coastal exploration.",
    itinerary: [
      {
        id: 1,
        heading: "Arrival",
        description: "Check-in and beach exploration",
      },
      {
        id: 2,
        heading: "Water Sports",
        description: "Thrilling water activities",
      },
    ],
    inclusions: ["Accomodation", "Breakfast", "Water Sports", "Guided Tours"],
    exclusions: ["Lunch & Dinner", "Personal expenses"],
    highlights: [
      "Beach Parties",
      "Water Sports",
      "Fort Aguada",
      "Spice Plantation",
    ],
  },
  {
    id: 5,
    img: "/kashmir.jpg",
    name: "Kashmir Paradise - Valleys & Dal Lake",
    slug: "kashmir-paradise",
    partner: "Capture A Trip",
    location: "Kashmir",
    duration: "6 Days",
    groupSize: "12-16",
    rating: "4.9",
    difficulty: "Moderate",
    startCity: "Srinagar",
    price: "21999",
    description:
      "Experience paradise on Earth with pristine valleys, Mughal gardens, and houseboat stays.",
    itinerary: [
      {
        id: 1,
        heading: "Srinagar Arrival",
        description: "Dal Lake and Mughal Gardens",
      },
      {
        id: 2,
        heading: "Gulmarg",
        description: "Cable car and snow activities",
      },
    ],
    inclusions: [
      "Accomodation",
      "Houseboat Stay",
      "Meals",
      "Shikara Ride",
      "Guide",
    ],
    exclusions: ["Gondola tickets", "Personal expenses"],
    highlights: ["Dal Lake", "Gulmarg", "Pahalgam", "Mughal Gardens"],
  },
  {
    id: 6,
    img: "/jaipur.jpg",
    name: "Rajasthan Royal Heritage Tour",
    slug: "rajasthan-royal-heritage",
    partner: "WanderOn",
    location: "Rajasthan",
    duration: "8 Days",
    groupSize: "15-20",
    rating: "4.8",
    difficulty: "Easy",
    startCity: "jaipur",
    price: "28999",
    description:
      "Explore the royal heritage of Rajasthan with majestic forts, palaces, and desert safaris.",
    itinerary: [
      {
        id: 1,
        heading: "Jaipur Arrival",
        description: "Pink City tour",
      },
      {
        id: 2,
        heading: "Jodhpur",
        description: "Blue City exploration",
      },
    ],
    inclusions: ["Accomodation", "Meals", "Transportation", "Guide"],
    exclusions: ["Monument fees", "Personal expenses"],
    highlights: ["Amber Fort", "City Palace", "Desert Safari", "Hawa Mahal"],
  },
];
